
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: db/development

production:
  <<: *default
  database: db/production
